### ISSUE TITLE
Link to package EventFlow.Outputs.Dynatrace in nuget returns 404 - not found

### ISSUE THREAD

**Issue by pchren** [Dynatrace/diagnostics-eventflow#1]
https://www.nuget.org/packages/Microsoft.Diagnostics.EventFlow.Outputs.Dynatrace/

Is this package still available?

**Comment by dtPaTh** [comment]
The project has never been merged back to the origin diagnostics-eventflow project. With that the package hasn't bee published and needs to be referenced from a local nuget repostiory when the project is built.
